In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from os import path
import sys

In [2]:
file_list = list(Path('./price_data').glob('*csv'))
file_name = path.basename(file_list[-1])

history = pd.read_csv('./histories.csv', encoding='sjis')

In [8]:
mcad = pd.read_csv('mcad.csv', encoding='sjis')
mcad = mcad[mcad['SC'].isin(list(history['SC']))]
df_e = pd.DataFrame()
df_e['SC'] = mcad['SC']
df_e['名称'] = mcad['名称']
df_e['prev_signal'] = mcad.loc[:, mcad.columns[-10]:mcad.columns[-2]].mean(axis=1)
df_e['latest_signal'] = mcad.loc[:, mcad.columns[-9]:mcad.columns[-1]].mean(axis=1)
df_e['prev_kairi'] = mcad[mcad.columns[-2]] - df_e['prev_signal']
df_e['latest_kairi'] = mcad[mcad.columns[-1]] - df_e['latest_signal']

In [9]:
df_e

,SC,名称,prev_signal,latest_signal,prev_kairi,latest_kairi
70,1776.0,三井住建道路,NaN,NaN,NaN,NaN
142,1938.0,日本リーテック,NaN,NaN,NaN,NaN
247,2216.0,カンロ,NaN,NaN,NaN,NaN
352,2459.0,アウンコンサルティング,10.008437,10.958074,6.070457,4.206362
422,2689.0,カワニシホールディングス,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
3479,9686.0,東洋テック,NaN,NaN,NaN,NaN
3523,9761.0,東海リース,NaN,NaN,NaN,NaN
3564,9846.0,天満屋ストア,NaN,NaN,NaN,NaN
3570,9857.0,英和,-0.711271,0.996312,9.765548,7.109050
3591,9904.0,ベリテ,3.089244,3.353165,1.092315,0.150071

In [7]:
mcad[mcad.columns[-2]]

70            NaN
142           NaN
247           NaN
352     16.078894
422           NaN
          ...
3479          NaN
3523          NaN
3564          NaN
3570     9.054277
3591     4.181560
Name: 20200611, Length: 98, dtype: float64