In [42]:
import pandas as pd
import numpy as np
from os import path
from pathlib import Path

In [43]:
df = pd.read_csv('./moving_average.csv', encoding='sjis')

In [44]:
file_list = list(Path('./price_data').glob('*csv'))
file_name = path.basename(file_list[-1])

In [45]:
l_df = pd.read_csv('./price_data/' + file_name, encoding='sjis')
l_df = l_df[['SC', '株価', '市場']]
l_df = l_df[l_df['市場'] == '東証一部']
l_df = l_df[l_df['市場'].isnull() == False]
l_df.drop(l_df.index[0:2], inplace=True)
l_df = l_df[l_df['株価'] != '-']
l_df['株価'] = l_df['株価'].astype(str).astype(np.float64)
l_df

        SC      株価    市場
4     1333  2201.0  東証一部
5     1352   904.0  東証一部
6     1376  1422.0  東証一部
7     1377  3445.0  東証一部
8     1379  1979.0  東証一部
...    ...     ...   ...
3780  9991   910.0  東証一部
3781  9993  1719.0  東証一部
3782  9994  2295.0  東証一部
3783  9995   448.0  東証一部
3785  9997   616.0  東証一部

[2167 rows x 3 columns]

In [48]:
#compare_data = pd.merge(df, l_df, on='SC', how='left')
compare_data = pd.merge(df, l_df, on='SC')
compare_data
#compare_data['compare'] = compare_data[compare_data.columns[-2]] - compare_data[compare_data.columns[-1]]

        SC      名称  20200612      株価    市場
0     1333  マルハニチロ   2295.60  2201.0  東証一部
1     1352    ホウスイ    915.12   904.0  東証一部
2     1376   カネコ種苗   1454.76  1422.0  東証一部
3     1377  サカタのタネ   3624.00  3445.0  東証一部
4     1379     ホクト   1989.40  1979.0  東証一部
...    ...     ...       ...     ...   ...
2162  9991    ジェコス    958.56   910.0  東証一部
2163  9993    ヤマザワ   1719.36  1719.0  東証一部
2164  9994     やまや   2248.80  2295.0  東証一部
2165  9995   グローセル    437.24   448.0  東証一部
2166  9997    ベルーナ    548.12   616.0  東証一部

[2167 rows x 5 columns]

In [50]:
compare_data.drop(compare_data.columns[-1], axis=1,inplace=True)
compare_data

        SC      名称  20200612      株価
0     1333  マルハニチロ   2295.60  2201.0
1     1352    ホウスイ    915.12   904.0
2     1376   カネコ種苗   1454.76  1422.0
3     1377  サカタのタネ   3624.00  3445.0
4     1379     ホクト   1989.40  1979.0
...    ...     ...       ...     ...
2162  9991    ジェコス    958.56   910.0
2163  9993    ヤマザワ   1719.36  1719.0
2164  9994     やまや   2248.80  2295.0
2165  9995   グローセル    437.24   448.0
2166  9997    ベルーナ    548.12   616.0

[2167 rows x 4 columns]

In [51]:
compare_data['compare'] = compare_data[compare_data.columns[-2]] - compare_data[compare_data.columns[-1]]

In [6]:
tmp_data = compare_data.loc[compare_data['compare'] > .0]
tmp_data['rate'] = tmp_data['compare'] / tmp_data[tmp_data.columns[-3]]

tmp_data2 = tmp_data.sort_values(by='rate', ascending=True)[0:20]

C:\Users\ficti\anaconda3\envs\DataScience\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [24]:
tmp_data2

        SC              名称  20200612      株価  compare      rate
2620  7433              伯東    990.04   990.0     0.04  0.000040
641   3171       マックスバリュ九州   2404.12  2404.0     0.12  0.000050
1726  5706          三井金属鉱業   2247.12  2247.0     0.12  0.000053
1697  5481          山陽特殊製鋼    997.08   997.0     0.08  0.000080
1492  4765        モーニングスター    371.04   371.0     0.04  0.000108
2859  7864  フジシールインターナショナル   2087.28  2087.0     0.28  0.000134
1015  3878           巴川製紙所    890.16   890.0     0.16  0.000180
420   2685          アダストリア   1701.32  1701.0     0.32  0.000188
3717  9993            ヤマザワ   1719.36  1719.0     0.36  0.000209
631   3154   メディアスホールディングス    953.24   953.0     0.24  0.000252
2988  8053            住友商事   1280.84  1280.5     0.34  0.000265
3260  8802            三菱地所   1722.00  1721.5     0.50  0.000290
2596  7313        テイ・エステック   3020.92  3020.0     0.92  0.000305
2357  6870        日本フェンオール   1300.40  1300.0     0.40  0.000308
1171  4208            宇部興産   1873.60  1873.0     0.60  0.000320
1334  4506         大日本住友製薬   1486.52  1486.0     0.52  0.000350
900   3666        テクノスジャパン    565.20   565.0     0.20  0.000354
25    1434   JESCOホールディングス    332.12   332.0     0.12  0.000361
2569  7266         今仙電機製作所    759.28   759.0     0.28  0.000369
3193  8541            愛媛銀行   1143.44  1143.0     0.44  0.000385

In [7]:
file_list = list(Path('./financial_data').glob('*csv'))
file_name = path.basename(file_list[-1])

In [8]:
financial_data = pd.read_csv('./financial_data/' + file_name, encoding='sjis')

In [9]:
financial_data.drop(financial_data.index[0:2], inplace=True)
financial_data = financial_data[financial_data['PER（予想）'] != '-']
financial_data['PER（予想）'] = financial_data['PER（予想）'].astype(str).astype(np.float64)

In [10]:

gyosyu_list = list(financial_data['業種'].unique())

class cat:
    def __init__(self, ave, std):
        self.ave = ave
        self.std = std

dictio = {}
for elm in gyosyu_list:
    # 平均
    #rint(financial_data[financial_data['業種'] == elm]['PER（予想）'].mean()
    #rint(financial_data[financial_data['業種'] == elm]['PER（予想）'].std())
    mean = financial_data[financial_data['業種'] == elm]['PER（予想）'].mean()
    std = financial_data[financial_data['業種'] == elm]['PER（予想）'].std()
    dictio[elm] = cat(mean, std)

financial_data['業種'] = financial_data['業種'].astype(str)

mean_list = []
std_list = []
for elm in list(dictio.keys()):
    mean_list.append(dictio[elm].ave)
    std_list.append(dictio[elm].std)
    

new_dic = {}
new_dic['業種'] = list(dictio.keys())
new_dic['平均'] = mean_list
new_dic['標準偏差'] = std_list
df = pd.DataFrame.from_dict(new_dic)
df['業種'] = df['業種'].astype(str)

In [11]:
test_data = pd.merge(financial_data, df, on='業種', how='left')

test_data['PER'] = (test_data['PER（予想）'] - test_data['平均']) / test_data['標準偏差']

In [12]:
test_data

,SC,名称,市場,業種,時価総額（百万円）,発行済株式数,配当利回り,1株配当,PER（予想）,PBR（実績）,...,BPS（実績）,最低購入額,単元株,高値日付,年初来高値,安値日付,年初来安値,平均,標準偏差,PER
0,1301,極洋,東証一部,水産・農林,29342,10928283,2.61,70,9.61,0.88,...,3046.26,268500,100,2020/1/21,2950,2020/3/13,2202,19.886000,9.380964,-1.095410
1,1332,日本水産,東証一部,水産・農林,152778,312430277,1.74,8.5,10.14,0.99,...,492.23,48900,100,2020/1/7,639,2020/3/13,398,19.886000,9.380964,-1.038912
2,1352,ホウスイ,東証一部,卸売,7575,8379000,2.21,20,18.92,1.19,...,760.43,90400,100,2020/1/7,1019,2020/3/16,633,28.166688,40.870663,-0.226243
3,1376,カネコ種苗,東証一部,水産・農林,16741,11772626,1.97,28,15.14,0.85,...,1673.24,142200,100,2020/4/6,1527,2020/3/13,869,19.886000,9.380964,-0.505918
4,1377,サカタのタネ,東証一部,水産・農林,163330,47410750,0.96,33,25.61,1.5,...,2302.05,344500,100,2020/5/19,3755,2020/3/17,2380,19.886000,9.380964,0.610172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1916,9983,ファーストリテイリング,東証一部,小売,6788714,106073656,0.75,480,65.33,6.4,...,9994.97,6400000,100,2020/6/10,66130,2020/3/19,39910,35.095577,38.074032,0.794096
1917,9989,サンドラッグ,東証一部,小売,413483,119331184,1.96,68,17.92,2.17,...,1597.57,346500,100,2020/1/17,4070,2020/3/23,2922,35.095577,38.074032,-0.451110
1918,9993,ヤマザワ,東証一部,小売,18842,10960825,1.57,27,170.37,0.67,...,2582.3,171900,100,2020/6/3,1735,2020/3/13,1121,35.095577,38.074032,3.552931
1919,9994,やまや,東証一部,小売,24896,10847870,2,46,12.44,0.73,...,3132.73,229500,100,2020/6/10,2350,2020/3/17,1821,35.095577,38.074032,-0.595040
1920,9997,ベルーナ,東証一部,小売,59903,97244472,2.6,16,11.45,0.58,...,1054.14,61600,100,2020/1/7,715,2020/3/19,393,35.095577,38.074032,-0.621042

In [14]:
test_data = test_data[['SC', 'PER', '市場']]
tmp_data3 = pd.merge(tmp_data2, test_data, on='SC')
tmp_data3

      SC              名称  20200612      株価  compare      rate       PER    市場
0   5706          三井金属鉱業   2247.12  2247.0     0.12  0.000053  0.578541  東証一部
1   7864  フジシールインターナショナル   2087.28  2087.0     0.28  0.000134 -0.286118  東証一部
2   9993            ヤマザワ   1719.36  1719.0     0.36  0.000209  3.552931  東証一部
3   3154   メディアスホールディングス    953.24   953.0     0.24  0.000252 -0.098523  東証一部
4   8802            三菱地所   1722.00  1721.5     0.50  0.000290  0.116730  東証一部
5   6870        日本フェンオール   1300.40  1300.0     0.40  0.000308 -0.447402  東証二部
6   4208            宇部興産   1873.60  1873.0     0.60  0.000320 -0.290928  東証一部
7   4506         大日本住友製薬   1486.52  1486.0     0.52  0.000350 -0.009036  東証一部
8   3666        テクノスジャパン    565.20   565.0     0.20  0.000354 -0.206918  東証一部
9   1434   JESCOホールディングス    332.12   332.0     0.12  0.000361 -0.183076  東証二部
10  8541            愛媛銀行   1143.44  1143.0     0.44  0.000385 -0.473383  東証一部

In [19]:
save_data = tmp_data3.sort_values(by='PER', ascending=True)[0:10]

In [20]:
save_data

      SC              名称  20200612      株価  compare      rate       PER    市場
10  8541            愛媛銀行   1143.44  1143.0     0.44  0.000385 -0.473383  東証一部
5   6870        日本フェンオール   1300.40  1300.0     0.40  0.000308 -0.447402  東証二部
6   4208            宇部興産   1873.60  1873.0     0.60  0.000320 -0.290928  東証一部
1   7864  フジシールインターナショナル   2087.28  2087.0     0.28  0.000134 -0.286118  東証一部
8   3666        テクノスジャパン    565.20   565.0     0.20  0.000354 -0.206918  東証一部
9   1434   JESCOホールディングス    332.12   332.0     0.12  0.000361 -0.183076  東証二部
3   3154   メディアスホールディングス    953.24   953.0     0.24  0.000252 -0.098523  東証一部
7   4506         大日本住友製薬   1486.52  1486.0     0.52  0.000350 -0.009036  東証一部
4   8802            三菱地所   1722.00  1721.5     0.50  0.000290  0.116730  東証一部
0   5706          三井金属鉱業   2247.12  2247.0     0.12  0.000053  0.578541  東証一部

In [21]:
reserve_data = save_data.drop([save_data.columns[-1], save_data.columns[-2]], axis=1)

In [22]:
reserve_data['reserve_price'] = (reserve_data[reserve_data.columns[2]] + 1.0).round()

In [23]:
reserve_data

      SC              名称  20200612      株価  compare      rate  reserve_price
10  8541            愛媛銀行   1143.44  1143.0     0.44  0.000385         1144.0
5   6870        日本フェンオール   1300.40  1300.0     0.40  0.000308         1301.0
6   4208            宇部興産   1873.60  1873.0     0.60  0.000320         1875.0
1   7864  フジシールインターナショナル   2087.28  2087.0     0.28  0.000134         2088.0
8   3666        テクノスジャパン    565.20   565.0     0.20  0.000354          566.0
9   1434   JESCOホールディングス    332.12   332.0     0.12  0.000361          333.0
3   3154   メディアスホールディングス    953.24   953.0     0.24  0.000252          954.0
7   4506         大日本住友製薬   1486.52  1486.0     0.52  0.000350         1488.0
4   8802            三菱地所   1722.00  1721.5     0.50  0.000290         1723.0
0   5706          三井金属鉱業   2247.12  2247.0     0.12  0.000053         2248.0