In [38]:
import pandas as pd
import numpy as np
from os import path
from pathlib import Path

#cat = '東証部'

df = pd.read_csv('./moving_average.csv', encoding='sjis')

file_list = list(Path('./price_data').glob('*csv'))
file_name = path.basename(file_list[-1])
# file_name

l_df = pd.read_csv('./price_data/' + file_name, encoding='sjis')

# 変更
l_df = l_df[['SC', '株価', '市場']]
l_df.drop(l_df.index[0:2], inplace=True)
#l_df = l_df[l_df['市場'] == cat]
l_df = l_df[l_df['市場'].isnull() == False]
l_df = l_df[l_df['株価'] != '-']
l_df['株価'] = l_df['株価'].astype(str).astype(np.float64)



# compare_data = pd.merge(df, l_df, on='SC', how='left')
compare_data = pd.merge(df, l_df, on='SC')
compare_data.drop(compare_data.columns[-1], axis=1,inplace=True)

compare_data['compare'] = compare_data[compare_data.columns[-2]] - compare_data[compare_data.columns[-1]]
# compare_data

tmp_data = compare_data.loc[compare_data['compare'] > .0]
tmp_data['rate'] = tmp_data['compare'] / tmp_data[tmp_data.columns[-3]]

# 結合した後のほうがいいか
# tmp_data2 = tmp_data.sort_values(by='rate', ascending=True)[0:20]
# tmp_data2

# 移動平均が上昇傾向のもののみを対象にする
tmp_data2 = tmp_data2[tmp_data2[tmp_data2.columns[2]] < tmp_data2[tmp_data2.columns[3]]]

file_list = list(Path('./financial_data').glob('*csv'))
file_name = path.basename(file_list[-1])
# file_name

financial_data = pd.read_csv('./financial_data/' + file_name, encoding='sjis')
# financial_data

C:\Users\ficti\anaconda3\envs\DataScience\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [39]:
financial_data

,SC,名称,市場,業種,時価総額（百万円）,発行済株式数,配当利回り,1株配当,PER（予想）,PBR（実績）,EPS（予想）,BPS（実績）,最低購入額,単元株,高値日付,年初来高値,安値日付,年初来安値
0,1,日経平均株価（日経225）,東証,株価指数,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1,2,TOPIX（東証株価指数）,東証,株価指数,-,-,-,-,-,-,-,-,-,-,-,-,-,-
2,1301,極洋,東証一部,水産・農林,29342,10928283,2.61,70,9.61,0.88,279.32,3046.26,268500,100,2020/1/21,2950,2020/3/13,2202
3,1332,日本水産,東証一部,水産・農林,152778,312430277,1.74,8.5,10.14,0.99,48.21,492.23,48900,100,2020/1/7,639,2020/3/13,398
4,1333,マルハニチロ,東証一部,水産・農林,115898,52656910,1.82,40,-,0.87,-,2520.27,220100,100,2020/1/17,2780,2020/3/13,1846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3781,9993,ヤマザワ,東証一部,小売,18842,10960825,1.57,27,170.37,0.67,10.09,2582.3,171900,100,2020/6/3,1735,2020/3/13,1121
3782,9994,やまや,東証一部,小売,24896,10847870,2,46,12.44,0.73,184.47,3132.73,229500,100,2020/6/10,2350,2020/3/17,1821
3783,9995,グローセル,東証一部,卸売,11839,26426800,2.68,12,-,0.48,-,934.79,44800,100,2020/1/24,477,2020/4/6,317
3784,9996,サトー商会,JQS,卸売,14928,9152640,-,-,-,0.62,-,2652.01,163100,100,2020/1/10,1736,2020/4/6,1310
3785,9997,ベルーナ,東証一部,小売,59903,97244472,2.6,16,11.45,0.58,53.8,1054.14,61600,100,2020/1/7,715,2020/3/19,393

In [40]:
financial_data.drop(financial_data.index[0:2], inplace=True)
financial_data = financial_data[financial_data['PBR（実績）'] != '-']
financial_data['PBR（実績）'] = financial_data['PBR（実績）'].astype(str).astype(np.float64)

test_data = test_data[['SC', 'PBR（実績）']]
tmp_data3 = pd.merge(tmp_data2, test_data, on='SC')
tmp_data3

C:\Users\ficti\anaconda3\envs\DataScience\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

     SC             名称  20200611  20200612      株価  compare      rate  PBR（実績）
0  6870       日本フェンオール   1292.84   1300.40  1300.0     0.40  0.000308     0.65
1  1434  JESCOホールディングス    330.40    332.12   332.0     0.12  0.000361     0.69
2  3449       テクノフレックス   1150.68   1164.48  1164.0     0.48  0.000412     1.16
3  5237            ノザワ    573.96    574.68   574.0     0.68  0.001183     0.41
4  7587         PALTEK    506.52    508.84   508.0     0.84  0.001651     0.59
5  4623          アサヒペン   1703.68   1703.84  1701.0     2.84  0.001667     0.57
6  2894           石井食品    216.40    216.60   216.0     0.60  0.002770     1.05
7  8912        エリアクエスト    102.68    103.36   103.0     0.36  0.003483     1.52

In [41]:
tmp_data3.shape

(8, 8)

In [43]:
tmp_data2.shape

(12, 7)

In [44]:
compare_data

       SC             名称  20200611  20200612      株価  compare
0    1434  JESCOホールディングス    330.40    332.12   332.0     0.12
1    1443     技研ホールディングス    322.56    322.20   301.0    21.20
2    1451            KHC    586.00    589.16   610.0   -20.84
3    1491           中外鉱業     17.24     17.32    18.0    -0.68
4    1711    省電舎ホールディングス    298.72    301.40   300.0     1.40
..    ...            ...       ...       ...     ...      ...
451  9929           平和紙業       NaN       NaN   400.0      NaN
452  9959   アシードホールディングス    406.12    407.24   408.0    -0.76
453  9967            堺商事       NaN       NaN  1545.0      NaN
454  9969          ショクブン    291.96    287.96   265.0    22.96
455  9980    MRKホールディングス    159.32    159.96   158.0     1.96

[456 rows x 6 columns]

In [45]:
tmp_data

       SC             名称  20200611  20200612      株価  compare      rate
0    1434  JESCOホールディングス    330.40    332.12   332.0     0.12  0.000361
1    1443     技研ホールディングス    322.56    322.20   301.0    21.20  0.065798
4    1711    省電舎ホールディングス    298.72    301.40   300.0     1.40  0.004645
10   1776         三井住建道路    796.68    797.36   777.0    20.36  0.025534
13   1844           大盛工業    227.76    227.64   219.0     8.64  0.037955
..    ...            ...       ...       ...     ...      ...       ...
436  9723          京都ホテル    615.52    618.08   612.0     6.08  0.009837
441  9799        旭情報サービス   1162.92   1163.72  1136.0    27.72  0.023820
448  9878            セキド    400.16    401.84   392.0     9.84  0.024487
454  9969          ショクブン    291.96    287.96   265.0    22.96  0.079733
455  9980    MRKホールディングス    159.32    159.96   158.0     1.96  0.012253

[128 rows x 7 columns]

In [46]:
save_data = tmp_data3.sort_values(by='PBR（実績）', ascending=True)[0:5]

In [47]:
save_data

     SC             名称  20200611  20200612      株価  compare      rate  PBR（実績）
3  5237            ノザワ    573.96    574.68   574.0     0.68  0.001183     0.41
5  4623          アサヒペン   1703.68   1703.84  1701.0     2.84  0.001667     0.57
4  7587         PALTEK    506.52    508.84   508.0     0.84  0.001651     0.59
0  6870       日本フェンオール   1292.84   1300.40  1300.0     0.40  0.000308     0.65
1  1434  JESCOホールディングス    330.40    332.12   332.0     0.12  0.000361     0.69