In [6]:
import pandas as pd
import numpy as np
from os import path
from pathlib import Path

# cat = '東証二部'

df = pd.read_csv('./moving_average.csv', encoding='sjis')

file_list = list(Path('./price_data').glob('*csv'))
file_name = path.basename(file_list[-1])
# file_name

l_df = pd.read_csv('./price_data/' + file_name, encoding='sjis')

# 変更
l_df = l_df[['SC', '株価', '市場']]
l_df.drop(l_df.index[0:2], inplace=True)
# l_df = l_df[l_df['市場'] == cat]
l_df = l_df[l_df['市場'].isnull() == False]
l_df = l_df[l_df['株価'] != '-']
l_df['株価'] = l_df['株価'].astype(str).astype(np.float64)

# 株価が1000以下のもののみ対象にする
l_df = l_df[l_df['株価'] < 1000.0]

# mcad > signal のもののみ
mcad = pd.read_csv('./mcad.csv', encoding='sjis')
df_e = pd.DataFrame()
df_e['SC'] = mcad['SC']
df_e['latest_signal'] = mcad.loc[:, mcad.columns[-9]:mcad.columns[-1]].mean(axis=1)
df_e['latest_mcad'] = mcad[mcad.columns[-1]]

l_df = pd.merge(l_df, df_e, on='SC')

In [7]:
l_df

        SC     株価    市場  latest_signal  latest_mcad
0     1332  492.0  東証一部       6.766344     2.724297
1     1352  901.0  東証一部      14.852195     7.845955
2     1380  819.0   JQS       2.406568     2.011600
3     1382  895.0   JQS            NaN          NaN
4     1384  634.0  東証一部       5.274370     1.790134
...    ...    ...   ...            ...          ...
1518  9980  166.0  東証二部       3.948727     2.494048
1519  9990  599.0  東証一部      12.816081    12.747470
1520  9991  970.0  東証一部      16.192648     8.108591
1521  9995  456.0  東証一部       9.778012     8.689830
1522  9997  628.0  東証一部      35.168565    34.049969

[1523 rows x 5 columns]

In [8]:
l_df = l_df[l_df['latest_mcad'] > l_df['latest_signal']]
l_df

        SC     株価    市場  latest_signal  latest_mcad
16    1446  719.0  東証一部      14.424091    26.842618
17    1447  665.0  東証マザ      23.448333    33.547153
20    1514  122.0  東証一部       1.921033     2.077988
25    1717  583.0  東証一部       7.229822     7.796515
28    1724  923.0   JQS       5.479445    11.033210
...    ...    ...   ...            ...          ...
1497  9854  220.0  東証一部       1.475568     1.596236
1499  9857  994.0  東証二部       9.520668    14.151592
1501  9876  289.0   JQS      37.655351    43.278631
1504  9885  377.0  東証二部       4.031942     5.140041
1505  9888  407.0   JQS       5.735618     5.825353

[190 rows x 5 columns]

In [11]:
l_df.drop([l_df.columns[-1], l_df.columns[-2]], axis=1, inplace=True)

C:\Users\ficti\anaconda3\envs\DataScience\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [12]:
l_df.shape

(190, 3)