In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('mcad.csv', encoding='sjis')
df

,SC,名称,20191217,20191218,20191219,20191220,20191223,20191224,20191225,20191226,20191227,20191230
0,1301,極洋,-29.664694,-28.942228,-29.083404,-29.101893,-29.183594,-28.276851,-27.962146,-26.599204,-24.430526,-20.378936
1,1332,日本水産,2.995617,3.087930,2.008256,1.458560,1.330353,2.172010,2.088727,2.478306,2.835061,2.842945
2,1333,マルハニチロ,-32.931761,-34.911756,-37.740394,-36.814222,-34.312928,-31.962194,-32.707777,-31.243971,-28.225388,-27.533047
3,1352,ホウスイ,7.828841,6.870993,5.643379,4.617262,3.441618,2.082447,0.355662,-0.841741,-0.972564,-0.665117
4,1376,カネコ種苗,-11.819472,-11.888122,-12.125518,-12.651963,-12.680921,-12.878186,-13.843243,-12.846142,-12.476948,-13.720719
...,...,...,...,...,...,...,...,...,...,...,...,...
3693,9987,スズケン,-196.180966,-201.528536,-203.022746,-202.278634,-198.991610,-191.755434,-189.086003,-181.249998,-173.444012,-171.334547
3694,9989,サンドラッグ,43.474551,43.511672,42.247175,43.567046,44.902363,47.830006,43.994627,40.488337,39.673000,34.194626
3695,9990,サックスバーホールディングス,1.496494,2.703298,4.335941,5.166805,5.599342,5.874414,5.305032,4.878251,4.488286,3.892293
3696,9991,ジェコス,45.725236,46.434839,45.982992,45.184730,43.725297,41.046536,39.596834,38.488414,38.218416,38.448835
3697,9993,ヤマザワ,-4.422776,-1.842250,0.918472,2.751875,4.555803,4.082460,3.665084,2.498592,2.513465,3.693055

## MCADの9日移動平均を求める

In [9]:
df_e = pd.DataFrame()
df_e['SC'] = df['SC']
df_e['名称'] = df['名称']
df_e['prev_signal'] = df.loc[:, df.columns[-10]:df.columns[-2]].mean(axis=1)
df_e['latest_signal'] = df.loc[:, df.columns[-9]:df.columns[-1]].mean(axis=1)
df_e

        SC              名称  prev_signal  latest_signal
0     1301              極洋   -28.138282     -27.106531
1     1332            日本水産     2.272758       2.255794
2     1333          マルハニチロ   -33.427821     -32.827964
3     1352            ホウスイ     3.225100       2.281327
4     1376           カネコ種苗   -12.578946     -12.790196
...    ...             ...          ...            ...
3693  9987            スズケン  -193.059771    -190.299058
3694  9989          サンドラッグ    43.298753      42.267650
3695  9990  サックスバーホールディングス     4.427540       4.693740
3696  9991            ジェコス    42.711477      41.902988
3697  9993            ヤマザワ     1.635636       2.537395

[3698 rows x 4 columns]

In [11]:
df_e['diff'] = df_e['prev_signal'] - df_e['latest_signal']
df_e['flg'] = df_e['diff'].apply(lambda x: 1 if x > 0 else 0)
df_e

        SC              名称  prev_signal  latest_signal      diff  flg
0     1301              極洋   -28.138282     -27.106531 -1.031751    0
1     1332            日本水産     2.272758       2.255794  0.016964    1
2     1333          マルハニチロ   -33.427821     -32.827964 -0.599857    0
3     1352            ホウスイ     3.225100       2.281327  0.943773    1
4     1376           カネコ種苗   -12.578946     -12.790196  0.211250    1
...    ...             ...          ...            ...       ...  ...
3693  9987            スズケン  -193.059771    -190.299058 -2.760713    0
3694  9989          サンドラッグ    43.298753      42.267650  1.031103    1
3695  9990  サックスバーホールディングス     4.427540       4.693740 -0.266200    0
3696  9991            ジェコス    42.711477      41.902988  0.808489    1
3697  9993            ヤマザワ     1.635636       2.537395 -0.901759    0

[3698 rows x 6 columns]